server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_LOCATION}
          timeout: 3
          search-paths: '{application}'
          default-label: main

encrypt:
  key-store:
    location: classpath:key/configKey.jks
    password: ${KEYSTORE_PASSWORD}
    alias: configKey
